<a href="https://colab.research.google.com/github/sindhu692/sindhu.py/blob/main/Student_marks_analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
print("Student marks analyszer\n")
print("Goal:Accept marks of multiple students using arrays")
import numpy
import numpy as np
stud1=int(input("Enter no of student:"))
sub1=int(input("Enter no of subjects:"))
l=[]
while True:


    for i in range(1,stud1+1):
        marks=input(f"Enter marks for student{i}: ").split(",")
        #marks=int(input("Enter marks of a student:"))
        temp=[]
        for m in marks:
            marks=int(m)
            temp.append(int(m))
        l.append(temp)

    break
arr=np.array(l)
print(arr)
print("----------------------------------")
print("student marks analyzer")
print("----------------------------------")

arr1=np.mean(arr,axis=1)
max_val=np.max(arr1)
for index,value in enumerate(arr1):
  print(f"student {index+1} avg {round(value,2)}")
  if max_val==value:
    print(f"Student {index+1} is the topper with avg of {max_val}")
  if value >=90:
    print("Grade A")
  elif value>=70:
    print("Grade B")
  elif value>=50:
    print("Grade C")
  elif value>=35:
    print("Grade D")
  else:
    print("Fail")
for t in range(arr.shape[1]):
  s=arr[:,t]
  s=np.max(arr[:,t])
  print(f"Highest marks in subject {t+1} as {s}")
  for i in range(arr.shape[0]):
    if arr[i][t]==s:
      print(f"student {i+1} is topper in subject {t+1} with {s}")

Student marks analyszer

Goal:Accept marks of multiple students using arrays
Enter no of student:3
Enter no of subjects:3
Enter marks for student1: 34,45,56
Enter marks for student2: 90,98,100
Enter marks for student3: 0,29,35
[[ 34  45  56]
 [ 90  98 100]
 [  0  29  35]]
----------------------------------
student marks analyzer
----------------------------------
----------------------------------
student 1 avg 45.0
Grade D
student 2 avg 96.0
Student 2 is the topper with avg of 96.0
Grade A
student 3 avg 21.33
Fail
Highest marks in subject 1 as 90
student 2 is topper in subject 1 with 90
Highest marks in subject 2 as 98
student 2 is topper in subject 2 with 98
Highest marks in subject 3 as 100
student 2 is topper in subject 3 with 100


Project Idea: Student Marks Analyzer using NumPy

🎯 Goal:
        Accept marks of multiple students using arrays

Use NumPy to analyze:

    Average

    Highest, Lowest

    Subject-wise Toppers

    Grade classification (above 75 = Distinction, etc.)

🧠 Sample Features:

    Input: Number of students & subjects

    Accept marks using NumPy array

Print:

    Each student’s average

    Subject-wise topper

    Class overall average

    Grade classification (with condition)

🧾 Example Output:

    Enter no. of students: 3
    Enter no. of subjects: 2

    Enter marks for student 1: 80 90
    Enter marks for student 2: 60 70
    Enter marks for student 3: 100 95

🎓 Results:

    Student 1: Avg = 85.0 -> Grade: Distinction
    Student 2: Avg = 65.0 -> Grade: First Class
    Student 3: Avg = 97.5 -> Grade: Distinction

    Subject 1 Topper: Student 3 (100)
    Subject 2 Topper: Student 3 (95)

    Class Average: 82.5
